# permissions for end users to edit resourcedetails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcedetails-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcedetails-editor-role
rules:
- apiGroups:
  - deskription.io
  resources:
  - resourcedetails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deskription.io
  resources:
  - resourcedetails/status
  verbs:
  - get
