# permissions for end users to view resourcetables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcetable-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcetable-viewer-role
rules:
- apiGroups:
  - deskription.io
  resources:
  - resourcetables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deskription.io
  resources:
  - resourcetables/status
  verbs:
  - get
