# permissions for end users to view resourcegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcegroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcegroup-viewer-role
rules:
- apiGroups:
  - deskription.io
  resources:
  - resourcegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deskription.io
  resources:
  - resourcegroups/status
  verbs:
  - get
