apiVersion: deskription.io/v1alpha1
kind: ResourceRelation
metadata:
  labels:
    app.kubernetes.io/name: resourcerelation
    app.kubernetes.io/instance: resourcerelation-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: resourcerelation-sample
spec:
  # TODO(user): Add fields here
